theme: jekyll-theme-cayman
title: test blog
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Talking about Software Engineering, Learning, and Side Hustles
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
